### PR TITLE
Use unchecked exception by default

### LINKED ISSUE #119: Consider unchecked exception as the default for Desc<JThrowable>
## Overview
Checked `j.l.Exception` is used as the default in `Desc<JThrowable>` implementations. Such exception cannot be thrown unless the Java native method declares it.

`j.l.RuntimeException` might be more appropriate, on the other hand, it might be reasonable to always require the callers to specify the exception type explicitly.

## Questions
1. [ ] Shall we allow to create an exception of a default type (e.g., `j.l.RuntimeException`) or always require to specify its type?

### PR DESCRIPTION
**Pull request by skletsun**
## Overview

This fixes #119 by using unchecked `java.lang.RuntimeException` as the default in `Desc<JThrowable>` implementations .

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Change is covered by automated [tests](https://github.com/jni-rs/jni-rs/blob/master/CONTRIBUTING.md#tests)
- [x] The [coding guidelines](https://github.com/jni-rs/jni-rs/blob/master/CONTRIBUTING.md#the-code-style) are followed
- [x] Public API has documentation
- [x] This change is not breaking **or** mentioned in the Changelog
- [x] The [continuous integration build](https://www.travis-ci.org/jni-rs/jni-rs) passes

### CODE REVIEW

File: tests/jni_api.rs [hunk 1]
```diff
@@ -611,8 +624,37 @@ fn assert_exception(res: Result<jobject, Error>, expect_message: &str) {
...
 }
 
-// Helper method that asserts there is a pending Java exception and clears if any
+// Shortcut to `assert_pending_java_exception_detailed()` without checking for expected  type and
+// message of exception.
 fn assert_pending_java_exception(env: &JNIEnv) {
+    assert_pending_java_exception_detailed(env, None, None)
+}
+
+// Helper method that asserts there is a pending Java exception of `expected_class` with
```
Comment (dmitry-timofeev) [inline tests/jni_api.rs]: expected_type

File: tests/jni_api.rs [hunk 2]
```diff
@@ -600,6 +592,27 @@ pub fn throw_new_fail() {
     assert_pending_java_exception(&env);
 }
 
+#[test]
+pub fn throw_defaults() {
+    let env = attach_current_thread();
+
+    assert_throws(&env, "Default exception thrown");
```
Comment (dmitry-timofeev) [inline tests/jni_api.rs]: Why don't we instead of throwing just use `JThrowable.lookup(env, "foo")` and then assert on the exception object (type + message)?

File: tests/jni_api.rs [hunk 3]
```diff
@@ -600,6 +592,27 @@ pub fn throw_new_fail() {
...
+    assert_throws(&env, "Default exception thrown".to_owned());
+    assert_throws(&env, JNIString::from("Default exception thrown"));
+}
+
+fn assert_throws<'a, D>(env: &JNIEnv<'a>, descriptor: D)
```
Comment (dmitry-timofeev) [inline tests/jni_api.rs]: This method does not only assert, it also performs the test itself, hence the name is slightly misleading. Also, it does not accept the expected values, but has them as locals, which is implicit and duplicates what is in `throw_defaults`.

I suggest making the expected value explicit, and passing the thing to assert on directly (or renaming this method to `test_throwable_descriptors_with_default_type(env, descriptor, expected_message)`). Or use constants.

File: tests/jni_api.rs (hunk 2 above)
Comment (skletsun) [reply tests/jni_api.rs]: Well, I wanted also to cover the `.throw()` itself (we have tests for `.throw_new()`, but nothing for `.throw()`), but probably it's not the best idea.

File: tests/jni_api.rs (hunk 3 above)
Comment (skletsun) [reply tests/jni_api.rs]: It looks better with constants.

File: tests/jni_api.rs [hunk 4]
```diff
@@ -25,6 +28,8 @@ static MATH_ABS_METHOD_NAME: &str = "abs";
 static MATH_TO_INT_METHOD_NAME: &str = "toIntExact";
 static MATH_ABS_SIGNATURE: &str = "(I)I";
 static MATH_TO_INT_SIGNATURE: &str = "(J)I";
+static DEFAULT_EXCEPTION_TYPE: &str = "java/lang/RuntimeException";
+static TEST_EXCEPTION_MESSAGE: &str = "Default exception thrown";
```
Comment (DarkEld3r) [inline tests/jni_api.rs]: It is slightly disturbing to see this duplicated constant. :upside_down_face:

Comment (skletsun) [reply tests/jni_api.rs]: Duplicated?.. 🤨

Comment (DarkEld3r) [reply tests/jni_api.rs]: There are `DEFAULT_EXCEPTION_CLASS` and `DEFAULT_EXCEPTION_TYPE` with the same value.

File: tests/jni_api.rs [hunk 5]
```diff
@@ -572,22 +577,11 @@ pub fn throw_new() {
...
-    let message = env
-        .call_method(ex, "getMessage", "()Ljava/lang/String;", &[])
-        .unwrap()
-        .l()
-        .unwrap();
-    let msg_rust: String = env.get_string(message.into()).unwrap().into();
-    assert_eq!(msg_rust, "Test Exception");
+    assert_pending_java_exception_detailed(
+        &env,
+        Some("java/lang/RuntimeException"),
```
Comment (DarkEld3r) [inline tests/jni_api.rs]: Should `DEFAULT_EXCEPTION_TYPE` be used here?

Comment (skletsun) [reply tests/jni_api.rs]: It's a different test and it is just a coincidence that it uses j.l.RuntimeException. Well... I see no reason making the `DEFAULT_EXCEPTION_CLASS` public. What if I define `RUNTIME_EXCEPTION_CLASS` (in analogue to the `EXCEPTION_CLASS` & `ARITHMETIC_EXCEPTION_CLASS`) and change all string representations to it (with no emphasis on default type of exception)?

Comment (skletsun) [reply tests/jni_api.rs]: Implemented in the suggested way.
