### PR TITLE
Fix safe methods checking exceptions

### LINKED ISSUE #114: Unnecessary check_exception after safe methods
## Overview
Some calls to [exception-safe](https://docs.oracle.com/javase/10/docs/specs/jni/design.html#exception-handling) methods check for exceptions afterwards, which either affects correctness or results in misleading logs.

## Description
Implementations of:
* ReleaseStringUTFChars()
* DeleteGlobalRef()
* PushLocalFrame()

check for exceptions after JNI calls. PushLocalFrame fails, the other two methods — print log messages (some of which misleading).

### How to reproduce
See https://github.com/jni-rs/jni-rs/compare/master...dmitry-timofeev:fix-safe-methods-checking-exceptions

### PR DESCRIPTION
**Pull request by dmitry-timofeev**
## Overview
Removes unnecessary `check_exception` from invocations of safe JNI methods.

Adds some regression tests.

Fixes #114 

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Change is covered by automated [tests](https://github.com/jni-rs/jni-rs/blob/master/CONTRIBUTING.md#tests)
- [x] The [coding guidelines](https://github.com/jni-rs/jni-rs/blob/master/CONTRIBUTING.md#the-code-style) are followed
- [x] Public API has documentation
- [x] This change is not breaking **or** mentioned in the Changelog
- [x] The [continuous integration build](https://www.travis-ci.org/jni-rs/jni-rs) passes

### CODE REVIEW

File: tests/jni_api.rs [hunk 1]
```diff
@@ -61,3 +62,94 @@ pub fn is_instance_of_null() {
...
+    // Try to allocate a frame of locals
+    env.with_local_frame(16, || {
+        Ok(JObject::null())
+    }).expect("JNIEnv#with_local_frame must work in case of pending exception");
+
+    env.exception_clear().unwrap();
+}
+
+
+// fixme: remove this test as it doesn't assert on anything — you can see
```
Comment (dmitry-timofeev) [inline tests/jni_api.rs]: Left for review in case you come up with a way to make it fail with a simple setup.

File: src/wrapper/jnienv.rs [hunk 2]
```diff
@@ -968,8 +971,8 @@ impl<'a> JNIEnv<'a> {
     #[allow(unused_unsafe)]
     pub unsafe fn release_string_utf_chars(&self, obj: JString, arr: *const c_char) -> Result<()> {
         non_null!(obj, "release_string_utf_chars obj argument");
+        // todo: use sth like 'jni_exception_safe_call'?
```
Comment (dmitry-timofeev) [inline src/wrapper/jnienv.rs]: Or just add a comment?

**Comment by dmitry-timofeev** [comment]
@vitvakatu , @alexander-irbis , @skletsun, @DarkEld3r , 

Would you review please? I specifically did not remove some fixmes — to give more context — I'll remove them afterwards.

File: src/wrapper/jnienv.rs (hunk 2 above)
Comment (vitvakatu) [reply src/wrapper/jnienv.rs]: I think a comment would suit better here.

Comment (dmitry-timofeev) [reply src/wrapper/jnienv.rs]: Now that I think of it, it might be better to use a separate macro for all such methods to express the intent clearly.

File: CHANGELOG.md [hunk 3]
```diff
@@ -15,6 +15,16 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 
 ## [Unreleased]
 
+### Changed
+- `push_local_frame`, `delete_global_ref` and `release_string_utf_chars`
+no longer check for exceptions as they are 
+[safe](https://docs.oracle.com/javase/10/docs/specs/jni/design.html#exception-handling)
+to call if there is a pending exception (#114):
```
Comment (vitvakatu) [inline CHANGELOG.md]: Not 114, but 124
